### ISSUE TITLE
WordPress 6.5

### ISSUE THREAD

**Issue by kyrapieterse** [maxi-blocks/maxi-blocks#5488]
Test it deep

**Comment by elzadj** [comment]
Deprecations: 

```select( 'core/edit-site' ).isInserterOpened is deprecated since version 6.5. Please use select( 'core/editor' ).isInserterOpened instead.```

```deprecated.js?ver=1a…2722e5853bb3a37:115 dispatch( 'core/edit-site' ).__experimentalSetPreviewDeviceType is deprecated since version 6.5 and will be removed in version 6.7. Note: registry.dispatch( editorStore ).setDeviceType```

**Comment by elzadj** [comment]
https://github.com/maxi-blocks/maxi-blocks/issues/5494

**Comment by elzadj** [comment]
```
index.js:190 Uncaught TypeError: Cannot read properties of null (reading 'frameElement')
    at index.js:190:11
    at mountMemo (react-dom.js?ver=18.2.0:17235:21)
    at Object.useMemo (react-dom.js?ver=18.2.0:17680:18)
    at useMemo (react.js?ver=18.2.0:1640:23)
    at Popover (index.js:188:29)
    at renderWithHooks (react-dom.js?ver=18.2.0:16315:20)
    at updateForwardRef (react-dom.js?ver=18.2.0:19236:22)
    at beginWork (react-dom.js?ver=18.2.0:21646:18)
    at HTMLUnknownElement.callCallback (react-dom.js?ver=18.2.0:4151:16)
    at Object.invokeGuardedCallbackDev (react-dom.js?ver=18.2.0:4200:18)
```

Sometimes happens when browsing patterns / blocks in the left sidebar

**Comment by elzadj** [comment]
```
[13-Mar-2024 12:29:40 UTC] PHP Fatal error:  Uncaught TypeError: array_merge_recursive(): Argument #1 must be of type array, null given in /home/elzadj/Work/Gutenberg/dev/wp-content/plugins/maxi-blocks/core/class-maxi-api.php:445
Stack trace:
#0 /home/elzadj/Work/Gutenberg/dev/wp-content/plugins/maxi-blocks/core/class-maxi-api.php(445): array_merge_recursive()
#1 /home/elzadj/Work/Gutenberg/dev/wp-content/plugins/maxi-blocks/core/class-maxi-styles.php(998): MaxiBlocks_API->post_maxi_blocks_styles()
#2 /home/elzadj/Work/Gutenberg/dev/wp-includes/class-wp-hook.php(324): MaxiBlocks_Styles->set_home_to_front_page()
#3 /home/elzadj/Work/Gutenberg/dev/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#4 /home/elzadj/Work/Gutenberg/dev/wp-includes/plugin.php(517): WP_Hook->do_action()
#5 /home/elzadj/Work/Gutenberg/dev/wp-includes/post.php(4828): do_action()
#6 /home/elzadj/Work/Gutenberg/dev/wp-includes/rest-api/endpoints/class-wp-rest-templates-controller.php(418): wp_insert_post()
#7 /home/elzadj/Work/Gutenberg/dev/wp-includes/rest-api/class-wp-rest-server.php(1230): WP_REST_Templates_Controller->create_item()
#8 /home/elzadj/Work/Gutenberg/dev/wp-includes/rest-api/class-wp-rest-server.php(1063): WP_REST_Server->respond_to_request()
#9 /home/elzadj/Work/Gutenberg/dev/wp-includes/rest-api/class-wp-rest-server.php(439): WP_REST_Server->dispatch()
#10 /home/elzadj/Work/Gutenberg/dev/wp-includes/rest-api.php(428): WP_REST_Server->serve_request()
#11 /home/elzadj/Work/Gutenberg/dev/wp-includes/class-wp-hook.php(324): rest_api_loaded()
#12 /home/elzadj/Work/Gutenberg/dev/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#13 /home/elzadj/Work/Gutenberg/dev/wp-includes/plugin.php(565): WP_Hook->do_action()
#14 /home/elzadj/Work/Gutenberg/dev/wp-includes/class-wp.php(418): do_action_ref_array()
#15 /home/elzadj/Work/Gutenberg/dev/wp-includes/class-wp.php(813): WP->parse_request()
#16 /home/elzadj/Work/Gutenberg/dev/wp-includes/functions.php(1336): WP->main()
#17 /home/elzadj/Work/Gutenberg/dev/wp-blog-header.php(16): wp()
#18 /home/elzadj/Work/Gutenberg/dev/index.php(17): require('...')
```

when trying to create a Front Page Template

**Comment by elzadj** [comment]
```
select( 'core/edit-site' ).isListViewOpened is deprecated since version 6.5. Please use select( 'core/editor' ).isListViewOpened instead. 
    at ResponsiveSelector (http://wordpress.local/wp-content/plugins/maxi-blocks/build/src_editor_responsive-selector_index_js.js:105:25)
    at InnerLoadable (http://wordpress.local/wp-content/plugins/maxi-blocks/build/index.js?ver=1.7.3:2329:34)
    at LoadableWithChunkExtractor
    at Loadable
    at ToolbarButtons (http://wordpress.local/wp-content/plugins/maxi-blocks/build/index.js?ver=1.7.3:64281:79)
```
