### ISSUE TITLE
WordPress 6.6

### ISSUE THREAD

**Issue by elzadj** [maxi-blocks/maxi-blocks#5608]
### Description

Maxi crashes on WP 6.6 beta 2

```
resolvers.js:4 Uncaught 
TypeError: Cannot read properties of undefined (reading 'mark')
    at ./src/extensions/store/resolvers.js (resolvers.js:4:22)
    at __webpack_require__ (bootstrap:19:1)
    at ./src/extensions/store/index.js (controls.js:37:24)
    at __webpack_require__ (bootstrap:19:1)
    at ./src/extensions/index.js (isInSiteEditorPreviewIframe.js:8:43)
    at __webpack_require__ (bootstrap:19:1)
    at ./src/index.js (index.js:18:28)
    at __webpack_require__ (bootstrap:19:1)
    at startup:4:92
    at __webpack_require__.O (chunk loaded:25:1)
edit-post.js?ver=87f…7a7280f58a3cba:3273 Warning: You are importing createRoot from "react-dom" which is not supported. You should instead import it from "react-dom/client"

```

https://make.wordpress.org/core/6-6/

18 June 2024	Beta 3. 
25 June 2024	Release candidate 1.
2 July 2024	Release candidate 2. 
9 July 2024	Release candidate 3.
15 July 2024	Dry run for release of WordPress 6.6 and 24-hour code freeze.
16 July 2024	WordPress 6.6 is released.

### Step-by-step reproduction instructions

1. Update to wp 6.6 beta 2
2. Open the editor
3. Check the console, also the blocks are broken

**Comment by elzadj** [comment]
Other issues: 
1. No maxi icon in the top toolbar
2. Cloud block is broken (patterns, icons, etc.)
3. The preview for maxi patterns in the left sidebar
